- hosts: all
  tasks:
    - name: Change the concurrency of Sidekiq
      become: yes
      template:
        src: templates/sidekiq.yml
        dest: mastodon/config/sidekiq.yml
        owner: root
        group: root
        mode: '0644'
